var _sptinit = { mask: 2555, account: '60', ga_tracker:'UA-41861406-4', rsc_path:'http://t.sellpoints.com/' , rsc_path_s:'https://t.sellpoints.com/' };
if (typeof product !== 'undefined'&& typeof product.identifier !== 'undefined' ) _sptinit.sku = product.identifier;
function sptobject_setPlgReady(l){sptobject.setPlgReady(l)}
var _spt=_spt||[],_gaq=_gaq||[],sptobject=function(){var l=this,L=window,k=navigator,T,U,V,m,w,A,q,W,B,C,r,X,O,D,Y,E,Z,h,p,g,n,t,u,x,v,y,s,M,F,G,H,ea=[],N,I,z,$=!1,J=void 0,P=L.globalStorage,Q,R=0,aa=[7,8,15,30,30,30,60,60,60,120,120,120],K,ba=!1,ca=Array.prototype.forEach,da=Array.prototype.map;try{var S=L.sessionStorage}catch(ga){}this.each=function(a,b,c){if(null!==a)if(ca&&a.forEach===ca)a.forEach(b,c);else if(a.length===+a.length)for(var e=0,f=a.length;e<f&&b.call(c,a[e],e,a)!=={};e++);else for(e in a)if(a.hasOwnProperty(e)&&
b.call(c,a[e],e,a)==={})break};this.map=function(a,b,c){var e=[];if(null==a)return e;if(da&&a.map===da)return a.map(b,c);this.each(a,function(a,fa,g){e[e.length]=b.call(c,a,fa,g)});return e};this.init=function(a){try{var b=document.readyState;if("interactive"===b||"complete"===b||m&4096){T=a&&a.rsc_path?a.rsc_path:"";U=a&&a.rsc_path_s?a.rsc_path_s:"";V=a&&a.ga_tracker?a.ga_tracker:"UA-41861406-6";w=["fl","sl"];A=[1,2];q=[!1,!1];W=[10,10];B=[void 0,void 0];C=[void 0,void 0];r=[void 0,void 0];X=["Shockwave Flash",
"Silverlight Plug-In"];O=["ShockwaveFlash.ShockwaveFlash","AgControl.AgControl"];D=["application/x-shockwave-flash","application/x-silverlight-2"];Y=["1.0.0.0","4.0.60310.0"];E=["sp_swfcontainer","sp_slcontainer"];Z=["spt.swf","spt.xap"];h=[void 0,void 0];p=[0,0];_plgFonts=[void 0,void 0];m=a&&a.mask?a.mask:void 0;s=y=v=x=u=t=n=g=void 0;z=-1!=k.appName.indexOf("Microsoft");if(!z)try{J=L.localStorage}catch(c){}F=M=null;H=a&&a.account?a.account:void 0;G=a&&a.sku?a.sku:void 0;N=a&&a.customdata?a.customdata:
void 0;I=a&&"undefined"!==typeof a.customdataevents?a.customdataevents:void 0;K=a&&a.cookiedomain&&0<location.hostname.indexOf(a.cookiedomain)?";domain="+a.cookiedomain:"";$=!0;G&&this.sp_heartBeat();this.sp_transaction()}else setTimeout(this.init,100,a)}catch(e){}};this.sp_testSkip=function(a,b,c){return!(a&m)||void 0!=b&&(void 0==c||b==c)};this.hasPlugIn=function(a,b,c,e){if(a==O[1]&&-1<k.userAgent.indexOf("Chrome"))return!1;if(void 0!=typeof k.plugins&&"object"==typeof k.plugins[b]){if((d=k.plugins[b].description)&&
void 0!=typeof k.mimeTypes&&k.mimeTypes[c]&&k.mimeTypes[c].enabledPlugin&&d[0]>=e)return!0}else if(void 0!=typeof L.ActiveXObject)try{var f=new ActiveXObject(a);if(f)try{if((d=f.GetVariable("$version"))&&d[0]>=e)return!0}catch(g){if(f.IsVersionSupported(e))return!0}}catch(h){}return!1};this.getPlgInInnerHTML=function(a){var b='<object id="'+E[a]+'" width="1" height="1"',c=("https:"==document.location.protocol?U:T)+Z[a];"fl"==w[a]?b=z?b+('classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"><param name="movie" value="'+
c+'"><object type="'+D[a]+'" data="'+c+'" width="1" height="1"><param name="movie" value="'+c+'"/></object></object>'):b+(D[a]+'" data="'+c+'" style="visibility: visible;"></object>'):"sl"==w[a]&&(b+='data="data:'+D[a]+'," type="'+D[a]+'"><param name="source" value="'+c+'"/><param name="autoUpgrade" value="false" /><param name="background" value="Transparent" /><param name="windowless" value="True" /><param name="minRuntimeVersion" value="4.0.0.0" /></object>');return b};this.createPlgElem=function(a){var b=
document.createElement("div");b.innerHTML=this.getPlgInInnerHTML(a);document.body.appendChild(b);return b};this.getPlgObject=function(a){if(r[a])return r[a];var b=z?window[E[a]]:document[E[a]];r[a]="sl"==w[a]?b.Content.App:b;return r[a]};this.sp_removePlg=function(a){if(!(7>p[a])){var b=document.getElementById(E[a]);b&&b.parentNode&&b.parentNode.removeChild(b);r[a]=void 0}};this.sp_id_plugin=function(a,b,c){if(!this.sp_testSkip(A[a],h[a],c)&&!B[a])try{if(b>W[a])B[a]=!0;else{B[a]=!1;var e=document.getElementById(E[a]);
b++;if(!r[a]){if(!q[a]){void 0===C[a]&&(C[a]=this.hasPlugIn(O[a],X[a],D[a],Y[a]));if(!C[a])return;e||this.createPlgElem(a);if(!q[a]){setTimeout(this.sp_id_plugin,300,a,b,c);return}}this.getPlgObject(a)}h[a]=r[a].getID();h[a]&1||(p[a]|=1);c&&h[a]!=c&&(h[a]&&this.sp_track({sp_g:"ns",type:w[a],old:h[a],newid:c}),r[a].setID(c),h[a]&2||(p[a]|=2),h[a]=c,this.sp_removePlg(a))}}catch(f){}};this.sp_id_window=function(a){if(!this.sp_testSkip(4,t,a))try{a?t!=a&&(t&&this.sp_track({sp_g:"ns",type:"wnm",old:t,
newid:a}),window.name.match(/[&]*spid=[0-9a-z-]*/i)?window.name=window.name.replace(/[&]*spid=[0-9a-z-]*/i,"&spid="+a):window.name+="&spid="+a,t=a):t=window.name.replace(/^.*[&]*spid=([0-9a-z-]*).*$/i,"$1")}catch(b){}};this.sp_id_userdata=function(a){if(!this.sp_testSkip(8,u,a))try{var b=document.getElementById("sp_udata");b||(b=document.createElement("div"),b.style.visibility="hidden",b.style.position="absolute",b.setAttribute("id","sp_udata"),document.body.appendChild(b),b.style.behavior="url(#default#userData)");
void 0!==a?u!=a&&(u&&this.sp_track({sp_g:"ns",type:"h5i",old:u,newid:a}),b.setAttribute("spid",a),b.save("spid"),u=a):(b.load("spid"),u=b.getAttribute("spid"))}catch(c){}};this.sp_id_local_storage=function(a){if(!this.sp_testSkip(32,v,a))try{J&&(void 0!==a?v!=a&&(v&&this.sp_track({sp_g:"ns",type:"h5l",old:v,newid:a}),J.setItem("spid",a),v=a):v=J.getItem("spid"))}catch(b){}};this.sp_id_database_storage=function(a){if(!this.sp_testSkip(128,s,a))try{if(window.openDatabase){var b=window.openDatabase("sqlite_sp_id",
"","sp_id",1048576);s!=a&&b.transaction(function(b){b.executeSql("CREATE TABLE IF NOT EXISTS cache(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,value TEXT NOT NULL,UNIQUE (name))",[],function(b,c){b.executeSql("SELECT value FROM cache WHERE name=?",["spid"],function(b,c){1<=c.rows.length&&(s=c.rows.item(0).value);s&&s!=g&&this.sp_track({sp_g:"ns",type:"h5d",old:s,newid:a});b.executeSql("INSERT OR REPLACE INTO cache(name, value) VALUES(?, ?)",["spid",a],function(b,c){s=a})})})})}}catch(c){}};
this.sp_id_session_storage=function(a){if(!this.sp_testSkip(16,x,a))try{S&&(void 0!==a?x!=a&&(x&&this.sp_track({sp_g:"ns",type:"h5s",old:x,newid:a}),S.setItem("spid",a)):x=S.getItem("spid"))}catch(b){}};this.sp_id_global_storage=function(a){if(!this.sp_testSkip(64,y,a)&&!J&&P){var b=window.location.host.replace(/:\d+/,"");try{void 0!==a?y!=a&&(y&&this.sp_track({sp_g:"ns",type:"h5g",old:y,newid:a}),P[b].spid=a):y=P[b].spid}catch(c){}}};this.sp_setCookie=function(a,b,c,e){var f=new Date;"y"===c?f.setDate(f.getDate()+
365):"h"===c?f.setMilliseconds(f.getMilliseconds()+36E5):f.setDate(f.getDate()-1);document.cookie=a+"="+b+"; expires="+f.toUTCString()+e+";path=/"};this.sp_id_cookie=function(a){if(void 0!==a)n!=a&&(n&&this.sp_track({sp_g:"ns",type:"ck",old:n,newid:a}),this.sp_setCookie("spid",a,"y",K));else if(!n){a=document.cookie;for(var b=/(?:[^a-z0-9;]*)spid[ ]*=([^;]*)/g,c=0,e;e=b.exec(a);){if(n&&e[1]!==n){var f=n;n=e[1];this.sp_track({sp_g:"ns",type:"ck",old:f,newid:e[1]})}else n=e[1];c++;if(10<c)break}1<=
c&&0<K.length&&(this.sp_setCookie("spid","","-",""),this.sp_setCookie("spid",n,"y",K))}};this.sp_getAllSPids=function(){var a=[];a.push(g,n,y,x,s,v,u,t);h&&h instanceof Array&&2==h.length&&a.push(h[0],h[1]);return a};this.sp_setToBestSPID=function(){var a=this.sp_getAllSPids();a:{for(var b=0;b<a.length;){if(a[b]){g=a[b];break a}b++}g=void 0}g&&"string"==typeof g&&g.match(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i)||(g=this.sp_uuidFast())};this.sp_IsInSession=function(){var a=
!1;if(ba||-1<document.cookie.indexOf("sp_ssid"))a=!0;ba=!0;this.sp_setCookie("sp_ssid","1","h",K);return a};this.sp_getSPID=function(){if(g)return g;this.sp_id_cookie();this.sp_id_session_storage();this.sp_id_global_storage();this.sp_id_window();this.sp_id_userdata();this.sp_id_local_storage();this.sp_setToBestSPID();this.sp_id_cookie(g);this.sp_id_session_storage(g);this.sp_id_global_storage(g);this.sp_id_window(g);this.sp_id_userdata(g);this.sp_id_local_storage(g);this.sp_id_plugin(0,0,g);this.sp_id_plugin(1,
0,g);this.sp_id_database_storage(g);return g};this.sp_sendFingerPrintData=function(a){a=a?a:0;a++;if(15>a&&A[0]&m&&!q[0]&&A[1]&m&&!q[1])void 0==B[0]&&this.sp_id_plugin(0,0),void 0==B[1]&&this.sp_id_plugin(1,0),setTimeout(this.sp_sendFingerPrintData,400,a);else{var b=[];b.lg=k.language;b.sc=screen.colorDepth;b.tz=(new Date).getTimezoneOffset();b.ss=!!window.sessionStorage;var c;try{c=!!scope.localStorage}catch(e){c=!0}b.ls=c;b.db=!!window.indexedDB;b.ab=typeof document.body.addBehavior;b.od=typeof window.openDatabase;
b.cp=k.cpuClass;b.pf=k.platform;b.tk=k.doNotTrack;b.ja=k.javaEnabled();b.rsl=screen.width+"x"+screen.height;b.plg=(C[0]?"t":"f")+"-"+(C[1]?"t":"f");c=!1;try{15>a&&A[0]&m&&q[0]&&(h[0]&4||(p[0]|=4),_plgFonts[0]||(_plgFonts[0]=sp_fnv_hash(this.getPlgObject(0).getFonts().join(";"))),b.ft="f"+_plgFonts[0],c=!0)}catch(f){}if(!c&&15>a&&A[1]&m&&q[1]){h[1]&4||(p[1]|=4);try{_plgFonts[1]||(_plgFonts[1]=sp_fnv_hash(this.getPlgObject(1).getFonts())),b.ft="s"+_plgFonts[1],c=!0}catch(g){}}c||(b.ft="");15>a&&(this.sp_removePlg(0),
this.sp_removePlg(1));a=this.map(k.plugins,function(a){var b=this.map(a,function(a){return[a.type,a.suffixes].join("~")}).join(",");return[a.name,a.description,b].join("::")},this).join(";");b.pg=sp_fnv_hash(a);b.sp_g="f";return this.sp_track(b)}};this.sp_appendCustomData=function(a){if("function"!=typeof N||"undefined"===typeof a)return!1;var b=N(a.sp_g);if(!b)return!1;if("object"==typeof b)for(var c in b)b.hasOwnProperty(c)&&(a instanceof Array?a.push(encodeURIComponent(c)+"="+encodeURIComponent(b[c])):
a[c]=b[c]);else a instanceof Array?a.push("customvalue="+b):a.customvalue=b;return!0};this.sp_sendCustomData=function(){if(I&&-1<I.indexOf("cd")){var a={sp_g:"cd"};this.sp_appendCustomData(a)&&this.sp_track(a)}};this.sp_sendFirstPartyData=function(){if(1024&m){var a={},b=0;document.cookie.replace(/([^=; ]+)=([^;]*)/gi,function(c,e,f){"spid"!=e&&"sp_ssid"!=e&&"spuid"!=e&&(a[e]=f,b++)});a.sp_g="c";this.sp_track(a)}};this.sp_fnv_hash=function(a){for(var b=2166136261,c=0,c=0;c<a.length;c++)b=16777619*
b^a.charCodeAt(c);return b};this.sp_void=function(a){};this.sp_track=function(a){try{if(!(k.doNotTrack&&m&8192)){var b=this.sp_IsInSession(),c=[];c.push("u="+this.sp_getSPID());c.push("r="+Math.random());c.push("v=1.06");G&&c.push("sku="+G);H&&c.push("rtlr="+H);var e="a",f;for(f in a)a.hasOwnProperty(f)&&("sp_g"==f?e=a[f]:c.push(encodeURIComponent(f)+"="+encodeURIComponent(a[f])));I&&-1<I.indexOf(e)&&this.sp_appendCustomData(c);c.push("ref="+encodeURIComponent(document.referrer));var g=location.protocol+
"//t.sellpoints.com/"+e+".gif?"+c.join("&").substr(0,4089);this.sp_pix(g);b||(this.sp_sendFingerPrintData(),this.sp_sendCustomData(),this.sp_sendFirstPartyData());return g}}catch(h){}};this.sp_track_i2=function(a){try{if(!(k.doNotTrack&&m&8192)){if(F&&(F!=a.a||"close"!=a.e)){var b=a.a,c=a.e;a.a=F;a.e="close";this.sp_track_i2(a);a.a=b;a.e=c}F=a.a;a.l||(a.l=G);if(a.l&&(a.e||(a.e="open"),a.a)){a.a+="-"+a.e;a.c||(a.c=H);a.t||(a.t=V);var e=this.sp_getSPID(),f=new Date,b=0;M&&(b=a.v?a.v:Math.round(Math.min((f-
M)/1E3,480),0));M=f;var g=encodeURIComponent(a.c+"|"+a.a+"|"+a.l);this.sp_pix("http://www.google-analytics.com/collect?v=1&t=event&ec="+encodeURIComponent(a.c)+"&ea="+a.a+"&el="+g+"&ev="+b+"&cid="+e+"&tid="+a.t+"&z="+Math.random());a.dt=b;this.sp_track(a);"close"==a.e&&(F=void 0)}}}catch(h){}};this.sp_pix=function(a){var b=new Image;b.width=1;b.border=0;b.src=a;b.onload=function(){l.sp_void(b)};m&4096&&ea.push(a)};this.sp_uuidFast=function(){for(var a="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split(""),
b=Array(36),c=0,e,f=0;36>f;f++)8==f||13==f||18==f||23==f?b[f]="-":14==f?b[f]="4":(2>=c&&(c=33554432+16777216*Math.random()|0),e=c&15,c>>=4,b[f]=a[19==f?e&3|8:e]);return b.join("")};this.sp_heartBeat=function(){try{Q||(Q=new Date),this.sp_track({sp_g:"h",t:Math.round((new Date-Q)/1E3,0)}),2048&m&&aa.length>R&&(setTimeout(this.sp_heartBeat,1E3*aa[R]),R++)}catch(a){}};this.sp_fireGATransaction=function(a){a&&a instanceof Array&&0!=a.length&&this.sp_track({sp_g:"t",orderid:a[1],aff_store:a[2],total:a[3],
tax:a[4],shipping:a[5],city:a[6],state_prov:a[7],country:a[8]})};this.sp_fireGAProduct=function(a){a&&a instanceof Array&&0!=a.length&&this.sp_track({sp_g:"tp",orderid:a[1],sku:a[2],product:a[3],category:a[4],price:a[5],count:a[6]})};this.sp_transaction_GA_like=function(a){var b=!1,c=void 0;try{c=a.slice(0)}catch(e){}if("undefined"!==typeof c&&c instanceof Array&&0<c.length)for(a=c.length-1;0<=a;a--)c[a]&&c[a]instanceof Array&&0<c[a].length&&("_addTrans"==c[a][0]?(this.sp_fireGATransaction(c[a]),
b=!0):"_addItem"==c[a][0]&&(this.sp_fireGAProduct(c[a]),b=!0));return b};this.sp_transaction_NewEgg=function(){var a=!1;if("undefined"!==typeof utag_data&&"undefined"!==typeof utag_data.trans_orders)for(var b=utag_data.trans_orders.length-1;0<=b;b--){var c=utag_data.trans_orders[b];this.sp_track({sp_g:"t",transid:utag_data.trans_id,orderid:c.order_id,total:c.order_total,tax:c.order_tax,shipping:c.order_shipping_charge,city:utag_data.trans_shipping_city,state_prov:utag_data.trans_shipping_state,country:utag_data.site_region,
zipcode:utag_data.trans_shipping_zipcode,customer_id:utag_data.customer_id,firstorder:utag_data.trans_first_order_flag});for(var a=!0,e=c.product_id.length-1;0<=e;e--)this.sp_track({sp_g:"tp",orderid:c.order_id,sku:c.product_id[e],product:c.product_title[e],category:c.product_subcategory[e],price:c.product_unit_price[e],sale_price:c.product_sale_price[e],count:c.product_quantity[e]})}return a};this.sp_transaction_AdWords=function(){var a=!1;if("undefined"!==typeof google_conversion_order_id&&"undefined"!==
typeof google_conversion_id&&google_conversion_order_id&&google_conversion_id&&(this.sp_track({sp_g:"t",orderid:google_conversion_order_id,total:google_conversion_value,numberitems:google_conversion_items&&google_conversion_items instanceof Array?google_conversion_items.length:0}),a=!0,google_conversion_items&&google_conversion_items instanceof Array))for(var b=google_conversion_items.length-1;0<=b;b--)this.sp_track({sp_g:"tp",orderid:google_conversion_order_id,sku:google_conversion_items[b].item_id,
price:google_conversion_items[b].value,count:google_conversion_items[b].quantity});return a};this.sp_transaction_GTS=function(){var a=!1;if(document.getElementById("gts-order")){var b=function(a){return(a=document.getElementById(a))&&void 0!==typeof a.innerHTML?a.innerHTML:""};b("gts-o-id")&&(this.sp_track({sp_g:"t",orderid:b("gts-o-id"),aff_store:b("gts-o-domain"),total:b("gts-o-total"),currency:b("gts-o-currency"),tax:b("gts-o-tax-total"),shipping:b("gts-o-shipping-total"),country:b("gts-o-country")}),
a=!0);var c=function(a,b){if(!a||"undefined"===typeof(z?a.querySelectorAll:a.getElementsByClassName))return"";var c=z?a.querySelectorAll("."+b):a.getElementsByClassName(b);return c&&1===c.length?c[0].innerHTML:null},e=z?document.querySelectorAll(".gts-item"):document.getElementsByClassName("gts-item");if(e)for(var f=e.length-1;0<=f;f--)this.sp_track({sp_g:"tp",orderid:b("gts-o-id"),sku:c(e[f],"gts-i-prodsearch-id"),product:c(e[f],"gts-i-name"),category:c(e[f],"gts-i-prodsearch-store-id"),price:c(e[f],
"gts-i-price"),count:c(e[f],"gts-i-quantity")})}return a};this.sptobject_push=function(a){var b=[];b.push(a);l.sp_transaction_GA_like(b)};this.sp_initSPTasObject=function(){var a=!1;_spt=function(b){if("undefined"!==typeof b&&!(b instanceof Array)&&null!==b)return b;var c=void 0;try{b instanceof Array&&(c=b.slice(0))}catch(e){}"undefined"!==typeof c&&c instanceof Array&&0<c.length&&(l.sp_transaction_GA_like(c),a=!0);return{push:function(a){try{l.sptobject_push(a)}catch(b){}}}}(_spt);return a};this.sp_transaction=
function(){$||this.init();this.sp_initSPTasObject()||this.sp_transaction_GA_like(_gaq)||this.sp_transaction_NewEgg()||this.sp_transaction_AdWords()||this.sp_transaction_GTS()};this.setPlgReady=function(a){switch(a){case w[0]:q[0]=!0;break;case w[1]:q[1]=!0}};this.setCustomData=function(a){N=a};this.setMask=function(a){m=a};this.setSKU=function(a){G=a};this.setRetailer=function(a){H=a};"undefined"!==typeof _sptinit&&this.init(_sptinit);return{init:function(a,b,c,e,f){try{l.init({mask:a,rsc_path:b,
ga_tracker:c,account:e,sku:f})}catch(g){}},initO:function(a){try{l.init(a)}catch(b){}},setPlgReady:function(a){try{l.setPlgReady(a)}catch(b){}},track:function(a){try{l.sp_track(a)}catch(b){}},i2track:function(a){try{l.sp_track_i2(a)}catch(b){}},setCustomData:function(a){try{l.setCustomData(a)}catch(b){}},setRetailer:function(a){try{l.setRetailer(a)}catch(b){}},setSKU:function(a){try{l.setSKU(a)}catch(b){}},trackGAConversion:function(){try{l.sp_transaction()}catch(a){}}}}();
